### ISSUE TITLE
Make sure to deploy your repos !

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [omarlamin01/vue-music-player#1]
You can deploy this repo for free on [https://vercel.com/](https://vercel.com/) and add the link to the repo 😉

**Comment by omarlamin01** [comment]
thank you for the tip, here is the link: https://omarlamin01-github-io-zsa2.vercel.app/

**Comment by abdellatif-laghjaj** [comment]
No need buddy,
I love it, just style it a little bit or I'll open a pull request Hahaha 🙂😂
